# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python\supermarket\sold.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_soldwindow(object):
    def setupUi(self, soldwindow):
        soldwindow.setObjectName("soldwindow")
        soldwindow.resize(800, 600)
        self.soldWidget = QtWidgets.QTableWidget(soldwindow)
        self.soldWidget.setGeometry(QtCore.QRect(10, 11, 751, 391))
        self.soldWidget.setObjectName("soldWidget")
        self.soldWidget.setColumnCount(4)
        self.soldWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.soldWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.soldWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.soldWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.soldWidget.setHorizontalHeaderItem(3, item)
        self.soldWidget.horizontalHeader().setDefaultSectionSize(187)
        self.soldWidget.verticalHeader().setDefaultSectionSize(37)
        self.soldWidget.verticalHeader().setMinimumSectionSize(30)
        self.sold_backbtn = QtWidgets.QPushButton(soldwindow)
        self.sold_backbtn.setGeometry(QtCore.QRect(660, 490, 93, 28))
        self.sold_backbtn.setObjectName("sold_backbtn")
        self.sold_btn = QtWidgets.QPushButton(soldwindow)
        self.sold_btn.setGeometry(QtCore.QRect(660, 450, 93, 28))
        self.sold_btn.setObjectName("sold_btn")

        self.retranslateUi(soldwindow)
        self.sold_backbtn.clicked.connect(soldwindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(soldwindow)

    def retranslateUi(self, soldwindow):
        _translate = QtCore.QCoreApplication.translate
        soldwindow.setWindowTitle(_translate("soldwindow", "sold"))
        item = self.soldWidget.horizontalHeaderItem(0)
        item.setText(_translate("soldwindow", "商品"))
        item = self.soldWidget.horizontalHeaderItem(1)
        item.setText(_translate("soldwindow", "售价"))
        item = self.soldWidget.horizontalHeaderItem(2)
        item.setText(_translate("soldwindow", "库存"))
        item = self.soldWidget.horizontalHeaderItem(3)
        item.setText(_translate("soldwindow", "出售件数"))
        self.sold_backbtn.setText(_translate("soldwindow", "返回"))
        self.sold_btn.setText(_translate("soldwindow", "确认出售"))
