# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python\supermarket\total.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 90, 295, 111))
        self.label.setSizeIncrement(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 230, 365, 52))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(42)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buy_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.buy_btn.setObjectName("buy_btn")
        self.horizontalLayout.addWidget(self.buy_btn)
        self.sold_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.sold_btn.setObjectName("sold_btn")
        self.horizontalLayout.addWidget(self.sold_btn)
        self.check_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout.addWidget(self.check_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.About_Author = QtWidgets.QAction(MainWindow)
        self.About_Author.setObjectName("About_Author")
        self.actionout = QtWidgets.QAction(MainWindow)
        self.actionout.setObjectName("actionout")
        self.Menu_Login = QtWidgets.QAction(MainWindow)
        self.Menu_Login.setObjectName("Menu_Login")
        self.Menu_Exit = QtWidgets.QAction(MainWindow)
        self.Menu_Exit.setObjectName("Menu_Exit")
        self.menuAbout.addAction(self.About_Author)
        self.menuMenu.addAction(self.Menu_Login)
        self.menuMenu.addAction(self.Menu_Exit)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.sold_btn.clicked.connect(MainWindow.close) # type: ignore
        self.buy_btn.clicked.connect(MainWindow.close) # type: ignore
        self.check_btn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "supermarket"))
        self.label.setText(_translate("MainWindow", "超市管理系统"))
        self.buy_btn.setText(_translate("MainWindow", "购入"))
        self.sold_btn.setText(_translate("MainWindow", "售出"))
        self.check_btn.setText(_translate("MainWindow", "存货"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.About_Author.setText(_translate("MainWindow", "Author"))
        self.actionout.setText(_translate("MainWindow", "out"))
        self.Menu_Login.setText(_translate("MainWindow", "Log in"))
        self.Menu_Exit.setText(_translate("MainWindow", "Exit"))
